name: Binary Search Unit Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        python -m unittest tests.test-binary  -v
    
    - name: Check test results
      if: always()
      uses: actions/github-script@v5
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const checkRuns = await github.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });

            const allJobsSucceeded = checkRuns.jobs.every(job => job.conclusion === 'success');
            if (!allJobsSucceeded) {
              core.setFailed('Some jobs failed');
            }