name: Binary Search Unit Tests

on:
  push:
    branches:
      - 'binary-search/*'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd Binary_Search
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        cd Binary_Search
        python -m unittest tests.test-binary -v
  